all:
	g++ -Wall -Wextra -std=c++17 -pedantic -mavx -g Stress.cpp -o Stress


# linux:
#	clang++ -Wall -Wextra -std=c++17 -pedantic -mavx -g Stress.cpp -o Stress -I/usr/include/kqueue/ -L/usr/lib/x86_64-linux-gnu/ -lkqueue -pthread